USE [master]
GO

/****** Object:  Database [tasksDB]    Script Date: 9/8/2013 1:00:17 PM ******/
CREATE DATABASE [tasksDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tasksDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\tasksDB.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'tasksDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\tasksDB_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [tasksDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tasksDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tasksDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [tasksDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [tasksDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [tasksDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [tasksDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [tasksDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [tasksDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [tasksDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [tasksDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tasksDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tasksDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [tasksDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [tasksDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tasksDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [tasksDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tasksDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [tasksDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tasksDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tasksDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tasksDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [tasksDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tasksDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [tasksDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tasksDB] SET RECOVERY FULL 
GO

ALTER DATABASE [tasksDB] SET  MULTI_USER 
GO

ALTER DATABASE [tasksDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tasksDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [tasksDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [tasksDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [tasksDB] SET  READ_WRITE 
GO

