//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimate
    {
        public int id { get; set; }
        public int time { get; set; }
        public string type { get; set; }
        public int taskId { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
